const Data = [
  {
    id: 1,
    coverImg: "/assets/images/statue.png",
    liked: false,
    numberOfLikes: 87,
    title: "STATUE OF ART",
    userIcon: "/assets/images/Rectangle-32.png",
    user: "Irakli N",
    price: 0.56236,
    raiting: "7/10",
    currency: "ETH",
  },
  {
    id: 2,
    coverImg: "/assets/images/Rectangle-26.png",
    liked: false,
    numberOfLikes: 77,
    title: "STATUE OF ART",
    userIcon: "/assets/images/elipse.png",
    user: "Irakli N",
    price: 1.54,
    raiting: "9/10",
    currency: "ETH",
  },
  {
    id: 3,
    coverImg: "/assets/images/Rectangle-32.png",
    liked: false,
    numberOfLikes: 107,
    title: "Colangle",
    userIcon: "/assets/images/elipse.png",
    user: "Irakli N",
    price: 75,
    raiting: "9/10",
    currency: "ETH",
  },
  {
    id: 4,
    coverImg: "/assets/images/Rectangle-35.png",
    liked: false,
    numberOfLikes: 92,
    title: "Virus K495",
    userIcon: "/assets/images/elipse.png",
    user: "Irakli N",
    price: 17.56,
    raiting: "9/10",
    currency: "ETH",
  },
  {
    id: 5,
    coverImg: "/assets/images/Rectangle-35.png",
    liked: false,
    numberOfLikes: 92,
    title: "Virus K495",
    userIcon: "/assets/images/elipse.png",
    user: "Irakli N",
    price: 17.56,
    raiting: "9/10",
    currency: "ETH",
  },
  {
    id: 6,
    coverImg: "/assets/images/Rectangle-35.png",
    liked: false,
    numberOfLikes: 92,
    title: "Virus K495",
    userIcon: "/assets/images/elipse.png",
    user: "Irakli N",
    price: 17.56,
    raiting: "9/10",
    currency: "ETH",
  },
  {
    id: 7,
    coverImg: "/assets/images/Rectangle-35.png",
    liked: false,
    numberOfLikes: 92,
    title: "Virus K495",
    userIcon: "/assets/images/elipse.png",
    user: "Irakli N",
    price: 17.56,
    raiting: "9/10",
    currency: "ETH",
  },
  {
    id: 8,
    coverImg: "/assets/images/Rectangle-35.png",
    liked: false,
    numberOfLikes: 92,
    title: "Virus K495",
    userIcon: "/assets/images/elipse.png",
    user: "Irakli N",
    price: 17.56,
    raiting: "9/10",
    currency: "ETH",
  },
  {
    id: 9,
    coverImg: "/assets/images/Rectangle-35.png",
    liked: false,
    numberOfLikes: 92,
    title: "Virus K495",
    userIcon: "/assets/images/elipse.png",
    user: "Irakli N",
    price: 17.56,
    raiting: "9/10",
    currency: "ETH",
  },
  {
    id: 10,
    coverImg: "/assets/images/Rectangle-35.png",
    liked: false,
    numberOfLikes: 92,
    title: "Virus K495",
    userIcon: "/assets/images/elipse.png",
    user: "Irakli N",
    price: 17.56,
    raiting: "9/10",
    currency: "ETH",
  },
  {
    id: 11,
    coverImg: "/assets/images/Rectangle-35.png",
    liked: false,
    numberOfLikes: 92,
    title: "Virus K495",
    userIcon: "/assets/images/elipse.png",
    user: "Irakli N",
    price: 17.56,
    raiting: "9/10",
    currency: "ETH",
  },
  {
    id: 12,
    coverImg: "/assets/images/Rectangle-35.png",
    liked: false,
    numberOfLikes: 92,
    title: "Virus K495",
    userIcon: "/assets/images/elipse.png",
    user: "Irakli N",
    price: 17.56,
    raiting: "9/10",
    currency: "ETH",
  },
];

export default Data;
